#+TITLE: Decomposition

** Divide and Conquer.
#+BEGIN_QUOTE
Life is like a spark between one vast darkness and another.Nor is the interval between the nights an unclouded day.
For the more pleasure we feel the more vulnarable we are to pain...
--- Alan Watts Wisdom Of Insecurity
#+END_QUOTE
Since the renaissance when science dropped its mystical hats and alchemical roots to become a
reductionist&rsquo;s game-- We have applied Francis Bacon's "scientific methodology" to all facets of human experience.
Trying to decompose and reduce all of life's mystery to its elementary substances, in the hope that this will reduce our anxieties about events out of our control.
These elements and methods of decomposition could then be used to rebuild our experiences and our the world in the images of our desires.
Understanding these disintegrational processes was the preserve of the god&rsquo;s.
As man built these grand babelic narratives,he gradually increased the average [[https://ourworldindata.org/life-expectancy][life expectancy]]  world over and in some areas overcoming the thought that diseases are demons.
Reductionism and unabated rationalism has creeped into most of western society and fields but has more or less stagnated
in growth in Africa with it&rsquo;s major mark being the still born African patriotism movement and like anything half baked, it is just general rhetoric.
This stagnation can be seen with the replacement of old African dieties with Western dieties and cultures whose genesis and philosophical underpinnings are mostly lost to the common Ugandan.
Once a person/society/idea fails to embrace change they start to cuddle with death.
Here lies the current pains of Uganda, stagnating since 2010 floating along the rising wave of globalisation but [[33   Link: https://www.reuters.com/article/us-uganda-internet-rights-trfn-idUSKBN29P1V8][not truly embracing it.]]
The country just concluded a  [[https://www.africanews.com/2020/06/24/inside-ugandas-proposed-scientific-election-analysis//][scientific election]] which if you're not aware of what type of election it is, it's one where political opponents are harrassed, arrested and stray bullets
start making their way to people's offices.

** Tradition and the society of the mind.
The only truth I know is that I am...Individuality is en vogue and everyone is encouraged to be creative and have independent thoughts (as if there ever is such a thing).
How is it possible to actually have independent thoughts? A mind that has lived is a mind that is polluted with thoughts that are not its own.
It's quiet easy to believe that you can easily control your thoughts but try 5 minutes of [[https://www.nytimes.com/guides/well/how-to-meditate][mindful meditation]].
You easily learn that your thoughts are products of processes within the brain and not only initiated by mere will(for those lucky to be able to direct their thoughts) leaving room for sporadic disjointed thoughts.
So man requires some ideas that are stable, ideas that are true and will always be true.
Tradition and gods had long filled this gap but as we have seen above but the science and it's method are slowly chipping away at it's hold on man.
Tradition atleast in historic societies was everything: religion, custom, laws all wrapped up into one little cocktail.
The creatives and individuals who then come a long to change the direction and never do it in isolation.

** No more resurrections.
 - With social media you have no death of your past/history especially for the millenials.
 - Internet in this generation is different from how the previous generation experienced internet.
